### ISSUE TITLE
我有点疑惑这句话是不是有问题

### ISSUE THREAD

**Issue by zanjie1999** [Kyomotoi/AnimeThesaurus#12]
json中有一个返回内容是  
`不行可以哦，只可以喜欢咱一个人`  
其中 `不行可以哦` 是什么意思（  
看了一下提交记录是初次提交的时候提交上来的呢~  
是不是有小可爱打错字了呢？

**Comment by Kyomotoi** [comment]
草，感谢提醒（
这就改这就改这就改
