### ISSUE TITLE
操作方法

### ISSUE THREAD

**Issue by 917017420** [Kyomotoi/AnimeThesaurus#21]
是直接复制到zhenxun_bot-main/data/anime.json 里面么

**Comment by Kyomotoi** [comment]
# 首先
我不是 zhenxun_bot 的开发者
# 其次
你应该去寻找对应的开发者，以获取详细且正常的安装方法

**Comment by Ink-33** [comment]
> 是直接复制到zhenxun_bot-main/data/anime.json 里面么
> 

@Hibikier

**Comment by HibiKier** [comment]
> 是直接复制到zhenxun_bot-main/data/anime.json 里面么

zhenxun中的anime.json是旧版，如果你要更新直接覆盖就行了
